# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-03-15 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fibseries',
            name='exec_time',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='fibseries',
            name='result',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
